// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gs2.Gs2Realtime.Message {

  /// <summary>Holder for reflection information generated from message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tZXNzYWdlLnByb3RvGhlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvItsC",
            "CglDb250YWluZXISKwoLbWVzc2FnZVR5cGUYASABKA4yFi5Db250YWluZXIu",
            "TWVzc2FnZVR5cGUSJQoHcGF5bG9hZBgCIAEoCzIULmdvb2dsZS5wcm90b2J1",
            "Zi5BbnkSEQoJc2lnbmF0dXJlGAMgASgMIuYBCgtNZXNzYWdlVHlwZRIRCg1I",
            "RUxMT19SRVFVRVNUEAASEAoMSEVMTE9fUkVTVUxUEAESDwoLQllFX1JFUVVF",
            "U1QQAhIeChZVUERBVEVfUFJPRklMRV9SRVFVRVNUEICAgIABEhkKEUpPSU5f",
            "Tk9USUZJQ0FUSU9OEICAgIACEhoKEkxFQVZFX05PVElGSUNBVElPThCBgICA",
            "AhIjChtVUERBVEVfUFJPRklMRV9OT1RJRklDQVRJT04QgoCAgAISFgoOQklO",
            "QVJZX01FU1NBR0UQgICAgAMSDQoFRVJST1IQ/////wcibgoRUlVEUFNlbmRD",
            "b250YWluZXISFAoMY29ubmVjdGlvbklkGAEgASgNEg4KBnNlY3JldBgCIAEo",
            "DRIUCgxwYWNrZXROdW1iZXIYAyABKA0SHQoJY29udGFpbmVyGAQgASgLMgou",
            "Q29udGFpbmVyInYKFFJVRFBSZWNlaXZlQ29udGFpbmVyEh8KF2xhc3RSZWNl",
            "aXZlUGFja2V0TnVtYmVyGAEgASgNEh4KFnJlY2VpdmVNZXNzYWdlQml0Rmxh",
            "Z3MYAiABKA0SHQoJY29udGFpbmVyGAMgASgLMgouQ29udGFpbmVyIj8KBlBs",
            "YXllchIUCgxjb25uZWN0aW9uSWQYASABKA0SDgoGdXNlcklkGAIgASgJEg8K",
            "B3Byb2ZpbGUYAyABKAwiNgoMSGVsbG9SZXF1ZXN0EhMKC2FjY2Vzc1Rva2Vu",
            "GAEgASgJEhEKCW15UHJvZmlsZRgCIAEoDCJTCgtIZWxsb1Jlc3VsdBIaCglt",
            "eVByb2ZpbGUYASABKAsyBy5QbGF5ZXISGAoHcGxheWVycxgCIAMoCzIHLlBs",
            "YXllchIOCgZzZWNyZXQYAyABKA0iDAoKQnllUmVxdWVzdCIpChRVcGRhdGVQ",
            "cm9maWxlUmVxdWVzdBIRCglteVByb2ZpbGUYASABKAwiLwoQSm9pbk5vdGlm",
            "aWNhdGlvbhIbCgpqb2luUGxheWVyGAEgASgLMgcuUGxheWVyIjEKEUxlYXZl",
            "Tm90aWZpY2F0aW9uEhwKC2xlYXZlUGxheWVyGAEgASgLMgcuUGxheWVyIjoK",
            "GVVwZGF0ZVByb2ZpbGVOb3RpZmljYXRpb24SHQoMdXBkYXRlUGxheWVyGAEg",
            "ASgLMgcuUGxheWVyIh0KDUJpbmFyeU1lc3NhZ2USDAoEZGF0YRgBIAEoDCI/",
            "CgVFcnJvchIRCgljb21wb25lbnQYASABKAkSEgoKc3RhdHVzQ29kZRgCIAEo",
            "DRIPCgdtZXNzYWdlGAMgASgJQjMKF2lvLmdzMi5yZWFsdGltZS5tZXNzYWdl",
            "qgIXR3MyLkdzMlJlYWx0aW1lLk1lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.Container), global::Gs2.Gs2Realtime.Message.Container.Parser, new[]{ "MessageType", "Payload", "Signature" }, null, new[]{ typeof(global::Gs2.Gs2Realtime.Message.Container.Types.MessageType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.RUDPSendContainer), global::Gs2.Gs2Realtime.Message.RUDPSendContainer.Parser, new[]{ "ConnectionId", "Secret", "PacketNumber", "Container" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.RUDPReceiveContainer), global::Gs2.Gs2Realtime.Message.RUDPReceiveContainer.Parser, new[]{ "LastReceivePacketNumber", "ReceiveMessageBitFlags", "Container" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.Player), global::Gs2.Gs2Realtime.Message.Player.Parser, new[]{ "ConnectionId", "UserId", "Profile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.HelloRequest), global::Gs2.Gs2Realtime.Message.HelloRequest.Parser, new[]{ "AccessToken", "MyProfile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.HelloResult), global::Gs2.Gs2Realtime.Message.HelloResult.Parser, new[]{ "MyProfile", "Players", "Secret" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.ByeRequest), global::Gs2.Gs2Realtime.Message.ByeRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.UpdateProfileRequest), global::Gs2.Gs2Realtime.Message.UpdateProfileRequest.Parser, new[]{ "MyProfile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.JoinNotification), global::Gs2.Gs2Realtime.Message.JoinNotification.Parser, new[]{ "JoinPlayer" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.LeaveNotification), global::Gs2.Gs2Realtime.Message.LeaveNotification.Parser, new[]{ "LeavePlayer" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.UpdateProfileNotification), global::Gs2.Gs2Realtime.Message.UpdateProfileNotification.Parser, new[]{ "UpdatePlayer" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.BinaryMessage), global::Gs2.Gs2Realtime.Message.BinaryMessage.Parser, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.Error), global::Gs2.Gs2Realtime.Message.Error.Parser, new[]{ "Component", "StatusCode", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// メッセージコンテナ
  /// </summary>
  public sealed partial class Container : pb::IMessage<Container> {
    private static readonly pb::MessageParser<Container> _parser = new pb::MessageParser<Container>(() => new Container());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Container(Container other) : this() {
      messageType_ = other.messageType_;
      payload_ = other.payload_ != null ? other.payload_.Clone() : null;
      signature_ = other.signature_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Container Clone() {
      return new Container(this);
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Gs2.Gs2Realtime.Message.Container.Types.MessageType messageType_ = 0;
    /// <summary>
    /// ペイロードの種類
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.Container.Types.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any payload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 3;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    /// <summary>
    /// payload の署名(事前に共有した鍵で作った HMAC-SHA256)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (!object.Equals(Payload, other.Payload)) return false;
      if (Signature != other.Signature) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != 0) hash ^= MessageType.GetHashCode();
      if (payload_ != null) hash ^= Payload.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MessageType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (payload_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Payload);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Container other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != 0) {
        MessageType = other.MessageType;
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          Payload = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Payload.MergeFrom(other.Payload);
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Gs2.Gs2Realtime.Message.Container.Types.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (payload_ == null) {
              Payload = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Payload);
            break;
          }
          case 26: {
            Signature = input.ReadBytes();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Container message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum MessageType {
        /// <summary>
        /// サインインリクエスト
        /// </summary>
        [pbr::OriginalName("HELLO_REQUEST")] HelloRequest = 0,
        /// <summary>
        /// サインインリザルト
        /// </summary>
        [pbr::OriginalName("HELLO_RESULT")] HelloResult = 1,
        /// <summary>
        /// サインアウトリクエスト
        /// </summary>
        [pbr::OriginalName("BYE_REQUEST")] ByeRequest = 2,
        /// <summary>
        /// プレイヤー情報更新
        /// </summary>
        [pbr::OriginalName("UPDATE_PROFILE_REQUEST")] UpdateProfileRequest = 268435456,
        /// <summary>
        /// プレイヤー参加通知
        /// </summary>
        [pbr::OriginalName("JOIN_NOTIFICATION")] JoinNotification = 536870912,
        /// <summary>
        /// プレイヤー離脱通知
        /// </summary>
        [pbr::OriginalName("LEAVE_NOTIFICATION")] LeaveNotification = 536870913,
        /// <summary>
        /// プレイヤー情報更新通知
        /// </summary>
        [pbr::OriginalName("UPDATE_PROFILE_NOTIFICATION")] UpdateProfileNotification = 536870914,
        /// <summary>
        /// バイナリメッセージ送信
        /// </summary>
        [pbr::OriginalName("BINARY_MESSAGE")] BinaryMessage = 805306368,
        /// <summary>
        /// エラー
        /// </summary>
        [pbr::OriginalName("ERROR")] Error = 2147483647,
      }

    }
    #endregion

  }

  /// <summary>
  /// RUDPコンテナ
  /// </summary>
  public sealed partial class RUDPSendContainer : pb::IMessage<RUDPSendContainer> {
    private static readonly pb::MessageParser<RUDPSendContainer> _parser = new pb::MessageParser<RUDPSendContainer>(() => new RUDPSendContainer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RUDPSendContainer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RUDPSendContainer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RUDPSendContainer(RUDPSendContainer other) : this() {
      connectionId_ = other.connectionId_;
      secret_ = other.secret_;
      packetNumber_ = other.packetNumber_;
      container_ = other.container_ != null ? other.container_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RUDPSendContainer Clone() {
      return new RUDPSendContainer(this);
    }

    /// <summary>Field number for the "connectionId" field.</summary>
    public const int ConnectionIdFieldNumber = 1;
    private uint connectionId_;
    /// <summary>
    /// 送信元プレイヤーのコネクションID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ConnectionId {
      get { return connectionId_; }
      set {
        connectionId_ = value;
      }
    }

    /// <summary>Field number for the "secret" field.</summary>
    public const int SecretFieldNumber = 2;
    private uint secret_;
    /// <summary>
    /// コネクションに割り当てられたシークレット
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Secret {
      get { return secret_; }
      set {
        secret_ = value;
      }
    }

    /// <summary>Field number for the "packetNumber" field.</summary>
    public const int PacketNumberFieldNumber = 3;
    private uint packetNumber_;
    /// <summary>
    /// パケット番号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PacketNumber {
      get { return packetNumber_; }
      set {
        packetNumber_ = value;
      }
    }

    /// <summary>Field number for the "container" field.</summary>
    public const int ContainerFieldNumber = 4;
    private global::Gs2.Gs2Realtime.Message.Container container_;
    /// <summary>
    /// ペイロード
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.Container Container {
      get { return container_; }
      set {
        container_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RUDPSendContainer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RUDPSendContainer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConnectionId != other.ConnectionId) return false;
      if (Secret != other.Secret) return false;
      if (PacketNumber != other.PacketNumber) return false;
      if (!object.Equals(Container, other.Container)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConnectionId != 0) hash ^= ConnectionId.GetHashCode();
      if (Secret != 0) hash ^= Secret.GetHashCode();
      if (PacketNumber != 0) hash ^= PacketNumber.GetHashCode();
      if (container_ != null) hash ^= Container.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ConnectionId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ConnectionId);
      }
      if (Secret != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Secret);
      }
      if (PacketNumber != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PacketNumber);
      }
      if (container_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Container);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConnectionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConnectionId);
      }
      if (Secret != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Secret);
      }
      if (PacketNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PacketNumber);
      }
      if (container_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Container);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RUDPSendContainer other) {
      if (other == null) {
        return;
      }
      if (other.ConnectionId != 0) {
        ConnectionId = other.ConnectionId;
      }
      if (other.Secret != 0) {
        Secret = other.Secret;
      }
      if (other.PacketNumber != 0) {
        PacketNumber = other.PacketNumber;
      }
      if (other.container_ != null) {
        if (container_ == null) {
          Container = new global::Gs2.Gs2Realtime.Message.Container();
        }
        Container.MergeFrom(other.Container);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConnectionId = input.ReadUInt32();
            break;
          }
          case 16: {
            Secret = input.ReadUInt32();
            break;
          }
          case 24: {
            PacketNumber = input.ReadUInt32();
            break;
          }
          case 34: {
            if (container_ == null) {
              Container = new global::Gs2.Gs2Realtime.Message.Container();
            }
            input.ReadMessage(Container);
            break;
          }
        }
      }
    }

  }

  public sealed partial class RUDPReceiveContainer : pb::IMessage<RUDPReceiveContainer> {
    private static readonly pb::MessageParser<RUDPReceiveContainer> _parser = new pb::MessageParser<RUDPReceiveContainer>(() => new RUDPReceiveContainer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RUDPReceiveContainer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RUDPReceiveContainer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RUDPReceiveContainer(RUDPReceiveContainer other) : this() {
      lastReceivePacketNumber_ = other.lastReceivePacketNumber_;
      receiveMessageBitFlags_ = other.receiveMessageBitFlags_;
      container_ = other.container_ != null ? other.container_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RUDPReceiveContainer Clone() {
      return new RUDPReceiveContainer(this);
    }

    /// <summary>Field number for the "lastReceivePacketNumber" field.</summary>
    public const int LastReceivePacketNumberFieldNumber = 1;
    private uint lastReceivePacketNumber_;
    /// <summary>
    /// 最後にプレイヤーから受信したパケット番号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint LastReceivePacketNumber {
      get { return lastReceivePacketNumber_; }
      set {
        lastReceivePacketNumber_ = value;
      }
    }

    /// <summary>Field number for the "receiveMessageBitFlags" field.</summary>
    public const int ReceiveMessageBitFlagsFieldNumber = 2;
    private uint receiveMessageBitFlags_;
    /// <summary>
    /// lastReceivePacketNumber - 1 から過去32回分のパケットを受信したかのフラグ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ReceiveMessageBitFlags {
      get { return receiveMessageBitFlags_; }
      set {
        receiveMessageBitFlags_ = value;
      }
    }

    /// <summary>Field number for the "container" field.</summary>
    public const int ContainerFieldNumber = 3;
    private global::Gs2.Gs2Realtime.Message.Container container_;
    /// <summary>
    /// ペイロード
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.Container Container {
      get { return container_; }
      set {
        container_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RUDPReceiveContainer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RUDPReceiveContainer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LastReceivePacketNumber != other.LastReceivePacketNumber) return false;
      if (ReceiveMessageBitFlags != other.ReceiveMessageBitFlags) return false;
      if (!object.Equals(Container, other.Container)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LastReceivePacketNumber != 0) hash ^= LastReceivePacketNumber.GetHashCode();
      if (ReceiveMessageBitFlags != 0) hash ^= ReceiveMessageBitFlags.GetHashCode();
      if (container_ != null) hash ^= Container.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LastReceivePacketNumber != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(LastReceivePacketNumber);
      }
      if (ReceiveMessageBitFlags != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ReceiveMessageBitFlags);
      }
      if (container_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Container);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LastReceivePacketNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LastReceivePacketNumber);
      }
      if (ReceiveMessageBitFlags != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ReceiveMessageBitFlags);
      }
      if (container_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Container);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RUDPReceiveContainer other) {
      if (other == null) {
        return;
      }
      if (other.LastReceivePacketNumber != 0) {
        LastReceivePacketNumber = other.LastReceivePacketNumber;
      }
      if (other.ReceiveMessageBitFlags != 0) {
        ReceiveMessageBitFlags = other.ReceiveMessageBitFlags;
      }
      if (other.container_ != null) {
        if (container_ == null) {
          Container = new global::Gs2.Gs2Realtime.Message.Container();
        }
        Container.MergeFrom(other.Container);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LastReceivePacketNumber = input.ReadUInt32();
            break;
          }
          case 16: {
            ReceiveMessageBitFlags = input.ReadUInt32();
            break;
          }
          case 26: {
            if (container_ == null) {
              Container = new global::Gs2.Gs2Realtime.Message.Container();
            }
            input.ReadMessage(Container);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// プレイヤー情報
  /// </summary>
  public sealed partial class Player : pb::IMessage<Player> {
    private static readonly pb::MessageParser<Player> _parser = new pb::MessageParser<Player>(() => new Player());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Player> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Player() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Player(Player other) : this() {
      connectionId_ = other.connectionId_;
      userId_ = other.userId_;
      profile_ = other.profile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Player Clone() {
      return new Player(this);
    }

    /// <summary>Field number for the "connectionId" field.</summary>
    public const int ConnectionIdFieldNumber = 1;
    private uint connectionId_;
    /// <summary>
    /// ユーザに割り当てられたコネクションID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ConnectionId {
      get { return connectionId_; }
      set {
        connectionId_ = value;
      }
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 2;
    private string userId_ = "";
    /// <summary>
    /// ユーザID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "profile" field.</summary>
    public const int ProfileFieldNumber = 3;
    private pb::ByteString profile_ = pb::ByteString.Empty;
    /// <summary>
    /// プロフィール情報を格納したバイナリ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Profile {
      get { return profile_; }
      set {
        profile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Player);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Player other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConnectionId != other.ConnectionId) return false;
      if (UserId != other.UserId) return false;
      if (Profile != other.Profile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConnectionId != 0) hash ^= ConnectionId.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Profile.Length != 0) hash ^= Profile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ConnectionId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ConnectionId);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      if (Profile.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Profile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConnectionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConnectionId);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Profile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Profile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Player other) {
      if (other == null) {
        return;
      }
      if (other.ConnectionId != 0) {
        ConnectionId = other.ConnectionId;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Profile.Length != 0) {
        Profile = other.Profile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConnectionId = input.ReadUInt32();
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
          case 26: {
            Profile = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class HelloRequest : pb::IMessage<HelloRequest> {
    private static readonly pb::MessageParser<HelloRequest> _parser = new pb::MessageParser<HelloRequest>(() => new HelloRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HelloRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelloRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelloRequest(HelloRequest other) : this() {
      accessToken_ = other.accessToken_;
      myProfile_ = other.myProfile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelloRequest Clone() {
      return new HelloRequest(this);
    }

    /// <summary>Field number for the "accessToken" field.</summary>
    public const int AccessTokenFieldNumber = 1;
    private string accessToken_ = "";
    /// <summary>
    /// ユーザIDを特定するのに使用する GS2アクセストークン
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AccessToken {
      get { return accessToken_; }
      set {
        accessToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "myProfile" field.</summary>
    public const int MyProfileFieldNumber = 2;
    private pb::ByteString myProfile_ = pb::ByteString.Empty;
    /// <summary>
    /// 自身のプロフィール情報を格納したバイナリ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString MyProfile {
      get { return myProfile_; }
      set {
        myProfile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HelloRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HelloRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccessToken != other.AccessToken) return false;
      if (MyProfile != other.MyProfile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AccessToken.Length != 0) hash ^= AccessToken.GetHashCode();
      if (MyProfile.Length != 0) hash ^= MyProfile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AccessToken.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccessToken);
      }
      if (MyProfile.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(MyProfile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AccessToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessToken);
      }
      if (MyProfile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MyProfile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HelloRequest other) {
      if (other == null) {
        return;
      }
      if (other.AccessToken.Length != 0) {
        AccessToken = other.AccessToken;
      }
      if (other.MyProfile.Length != 0) {
        MyProfile = other.MyProfile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AccessToken = input.ReadString();
            break;
          }
          case 18: {
            MyProfile = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class HelloResult : pb::IMessage<HelloResult> {
    private static readonly pb::MessageParser<HelloResult> _parser = new pb::MessageParser<HelloResult>(() => new HelloResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HelloResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelloResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelloResult(HelloResult other) : this() {
      myProfile_ = other.myProfile_ != null ? other.myProfile_.Clone() : null;
      players_ = other.players_.Clone();
      secret_ = other.secret_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelloResult Clone() {
      return new HelloResult(this);
    }

    /// <summary>Field number for the "myProfile" field.</summary>
    public const int MyProfileFieldNumber = 1;
    private global::Gs2.Gs2Realtime.Message.Player myProfile_;
    /// <summary>
    /// 自身のプレイヤー情報
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.Player MyProfile {
      get { return myProfile_; }
      set {
        myProfile_ = value;
      }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Gs2.Gs2Realtime.Message.Player> _repeated_players_codec
        = pb::FieldCodec.ForMessage(18, global::Gs2.Gs2Realtime.Message.Player.Parser);
    private readonly pbc::RepeatedField<global::Gs2.Gs2Realtime.Message.Player> players_ = new pbc::RepeatedField<global::Gs2.Gs2Realtime.Message.Player>();
    /// <summary>
    /// すでにギャザリングに参加しているプレイヤーのプレイヤー情報
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Gs2.Gs2Realtime.Message.Player> Players {
      get { return players_; }
    }

    /// <summary>Field number for the "secret" field.</summary>
    public const int SecretFieldNumber = 3;
    private uint secret_;
    /// <summary>
    /// RUDP を用いた通信で使用するシークレットキー
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Secret {
      get { return secret_; }
      set {
        secret_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HelloResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HelloResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MyProfile, other.MyProfile)) return false;
      if(!players_.Equals(other.players_)) return false;
      if (Secret != other.Secret) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (myProfile_ != null) hash ^= MyProfile.GetHashCode();
      hash ^= players_.GetHashCode();
      if (Secret != 0) hash ^= Secret.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (myProfile_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MyProfile);
      }
      players_.WriteTo(output, _repeated_players_codec);
      if (Secret != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Secret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (myProfile_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MyProfile);
      }
      size += players_.CalculateSize(_repeated_players_codec);
      if (Secret != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Secret);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HelloResult other) {
      if (other == null) {
        return;
      }
      if (other.myProfile_ != null) {
        if (myProfile_ == null) {
          MyProfile = new global::Gs2.Gs2Realtime.Message.Player();
        }
        MyProfile.MergeFrom(other.MyProfile);
      }
      players_.Add(other.players_);
      if (other.Secret != 0) {
        Secret = other.Secret;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (myProfile_ == null) {
              MyProfile = new global::Gs2.Gs2Realtime.Message.Player();
            }
            input.ReadMessage(MyProfile);
            break;
          }
          case 18: {
            players_.AddEntriesFrom(input, _repeated_players_codec);
            break;
          }
          case 24: {
            Secret = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ByeRequest : pb::IMessage<ByeRequest> {
    private static readonly pb::MessageParser<ByeRequest> _parser = new pb::MessageParser<ByeRequest>(() => new ByeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ByeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ByeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ByeRequest(ByeRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ByeRequest Clone() {
      return new ByeRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ByeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ByeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ByeRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class UpdateProfileRequest : pb::IMessage<UpdateProfileRequest> {
    private static readonly pb::MessageParser<UpdateProfileRequest> _parser = new pb::MessageParser<UpdateProfileRequest>(() => new UpdateProfileRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateProfileRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileRequest(UpdateProfileRequest other) : this() {
      myProfile_ = other.myProfile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileRequest Clone() {
      return new UpdateProfileRequest(this);
    }

    /// <summary>Field number for the "myProfile" field.</summary>
    public const int MyProfileFieldNumber = 1;
    private pb::ByteString myProfile_ = pb::ByteString.Empty;
    /// <summary>
    /// 自身のプロフィール情報を格納したバイナリ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString MyProfile {
      get { return myProfile_; }
      set {
        myProfile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateProfileRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateProfileRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MyProfile != other.MyProfile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MyProfile.Length != 0) hash ^= MyProfile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MyProfile.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(MyProfile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MyProfile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MyProfile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateProfileRequest other) {
      if (other == null) {
        return;
      }
      if (other.MyProfile.Length != 0) {
        MyProfile = other.MyProfile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MyProfile = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class JoinNotification : pb::IMessage<JoinNotification> {
    private static readonly pb::MessageParser<JoinNotification> _parser = new pb::MessageParser<JoinNotification>(() => new JoinNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JoinNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinNotification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinNotification(JoinNotification other) : this() {
      joinPlayer_ = other.joinPlayer_ != null ? other.joinPlayer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinNotification Clone() {
      return new JoinNotification(this);
    }

    /// <summary>Field number for the "joinPlayer" field.</summary>
    public const int JoinPlayerFieldNumber = 1;
    private global::Gs2.Gs2Realtime.Message.Player joinPlayer_;
    /// <summary>
    /// 新しく参加したプレイヤーのプレイヤー情報
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.Player JoinPlayer {
      get { return joinPlayer_; }
      set {
        joinPlayer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JoinNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JoinNotification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(JoinPlayer, other.JoinPlayer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (joinPlayer_ != null) hash ^= JoinPlayer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (joinPlayer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(JoinPlayer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (joinPlayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(JoinPlayer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JoinNotification other) {
      if (other == null) {
        return;
      }
      if (other.joinPlayer_ != null) {
        if (joinPlayer_ == null) {
          JoinPlayer = new global::Gs2.Gs2Realtime.Message.Player();
        }
        JoinPlayer.MergeFrom(other.JoinPlayer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (joinPlayer_ == null) {
              JoinPlayer = new global::Gs2.Gs2Realtime.Message.Player();
            }
            input.ReadMessage(JoinPlayer);
            break;
          }
        }
      }
    }

  }

  public sealed partial class LeaveNotification : pb::IMessage<LeaveNotification> {
    private static readonly pb::MessageParser<LeaveNotification> _parser = new pb::MessageParser<LeaveNotification>(() => new LeaveNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaveNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveNotification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveNotification(LeaveNotification other) : this() {
      leavePlayer_ = other.leavePlayer_ != null ? other.leavePlayer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveNotification Clone() {
      return new LeaveNotification(this);
    }

    /// <summary>Field number for the "leavePlayer" field.</summary>
    public const int LeavePlayerFieldNumber = 1;
    private global::Gs2.Gs2Realtime.Message.Player leavePlayer_;
    /// <summary>
    /// 離脱したプレイヤーのプレイヤー情報
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.Player LeavePlayer {
      get { return leavePlayer_; }
      set {
        leavePlayer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaveNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaveNotification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LeavePlayer, other.LeavePlayer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (leavePlayer_ != null) hash ^= LeavePlayer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (leavePlayer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LeavePlayer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (leavePlayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeavePlayer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaveNotification other) {
      if (other == null) {
        return;
      }
      if (other.leavePlayer_ != null) {
        if (leavePlayer_ == null) {
          LeavePlayer = new global::Gs2.Gs2Realtime.Message.Player();
        }
        LeavePlayer.MergeFrom(other.LeavePlayer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (leavePlayer_ == null) {
              LeavePlayer = new global::Gs2.Gs2Realtime.Message.Player();
            }
            input.ReadMessage(LeavePlayer);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateProfileNotification : pb::IMessage<UpdateProfileNotification> {
    private static readonly pb::MessageParser<UpdateProfileNotification> _parser = new pb::MessageParser<UpdateProfileNotification>(() => new UpdateProfileNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateProfileNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileNotification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileNotification(UpdateProfileNotification other) : this() {
      updatePlayer_ = other.updatePlayer_ != null ? other.updatePlayer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileNotification Clone() {
      return new UpdateProfileNotification(this);
    }

    /// <summary>Field number for the "updatePlayer" field.</summary>
    public const int UpdatePlayerFieldNumber = 1;
    private global::Gs2.Gs2Realtime.Message.Player updatePlayer_;
    /// <summary>
    /// 更新されたプレイヤー情報
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.Player UpdatePlayer {
      get { return updatePlayer_; }
      set {
        updatePlayer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateProfileNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateProfileNotification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UpdatePlayer, other.UpdatePlayer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (updatePlayer_ != null) hash ^= UpdatePlayer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (updatePlayer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpdatePlayer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (updatePlayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatePlayer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateProfileNotification other) {
      if (other == null) {
        return;
      }
      if (other.updatePlayer_ != null) {
        if (updatePlayer_ == null) {
          UpdatePlayer = new global::Gs2.Gs2Realtime.Message.Player();
        }
        UpdatePlayer.MergeFrom(other.UpdatePlayer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (updatePlayer_ == null) {
              UpdatePlayer = new global::Gs2.Gs2Realtime.Message.Player();
            }
            input.ReadMessage(UpdatePlayer);
            break;
          }
        }
      }
    }

  }

  public sealed partial class BinaryMessage : pb::IMessage<BinaryMessage> {
    private static readonly pb::MessageParser<BinaryMessage> _parser = new pb::MessageParser<BinaryMessage>(() => new BinaryMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BinaryMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BinaryMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BinaryMessage(BinaryMessage other) : this() {
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BinaryMessage Clone() {
      return new BinaryMessage(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// バイナリデータ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BinaryMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BinaryMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BinaryMessage other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Error : pb::IMessage<Error> {
    private static readonly pb::MessageParser<Error> _parser = new pb::MessageParser<Error>(() => new Error());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Error> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.MessageReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Error() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Error(Error other) : this() {
      component_ = other.component_;
      statusCode_ = other.statusCode_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Error Clone() {
      return new Error(this);
    }

    /// <summary>Field number for the "component" field.</summary>
    public const int ComponentFieldNumber = 1;
    private string component_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Component {
      get { return component_; }
      set {
        component_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 2;
    private uint statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Error);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Error other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Component != other.Component) return false;
      if (StatusCode != other.StatusCode) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Component.Length != 0) hash ^= Component.GetHashCode();
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Component.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Component);
      }
      if (StatusCode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(StatusCode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Component.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Component);
      }
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StatusCode);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Error other) {
      if (other == null) {
        return;
      }
      if (other.Component.Length != 0) {
        Component = other.Component;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Component = input.ReadString();
            break;
          }
          case 16: {
            StatusCode = input.ReadUInt32();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
