// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: plugin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gs2.Gs2Realtime.Message {

  /// <summary>Holder for reflection information generated from plugin.proto</summary>
  public static partial class PluginReflection {

    #region Descriptor
    /// <summary>File descriptor for plugin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PluginReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxwbHVnaW4ucHJvdG8aGWdvb2dsZS9wcm90b2J1Zi9hbnkucHJvdG8imwIK",
            "D1BsdWdpbkNvbnRhaW5lchIxCgttZXNzYWdlVHlwZRgBIAEoDjIcLlBsdWdp",
            "bkNvbnRhaW5lci5NZXNzYWdlVHlwZRIlCgdwYXlsb2FkGAMgASgLMhQuZ29v",
            "Z2xlLnByb3RvYnVmLkFueSKtAQoLTWVzc2FnZVR5cGUSGgoWUkVDRUlWRV9C",
            "SU5BUllfTUVTU0FHRRAAEhcKE1NFTkRfQklOQVJZX01FU1NBR0UQARIZChFK",
            "T0lOX05PVElGSUNBVElPThCAgICAAhIaChJMRUFWRV9OT1RJRklDQVRJT04Q",
            "gYCAgAISIwobVVBEQVRFX1BST0ZJTEVfTk9USUZJQ0FUSU9OEIKAgIACEg0K",
            "BUVSUk9SEP////8HIjoKFFJlY2VpdmVCaW5hcnlNZXNzYWdlEhQKDGNvbm5l",
            "Y3Rpb25JZBgCIAEoDRIMCgRkYXRhGAEgASgMIj0KEVNlbmRCaW5hcnlNZXNz",
            "YWdlEgwKBGRhdGEYASABKAwSGgoSdGFyZ2V0Q29ubmVjdGlvbklkGAIgAygN",
            "QjMKF2lvLmdzMi5yZWFsdGltZS5tZXNzYWdlqgIXR3MyLkdzMlJlYWx0aW1l",
            "Lk1lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.PluginContainer), global::Gs2.Gs2Realtime.Message.PluginContainer.Parser, new[]{ "MessageType", "Payload" }, null, new[]{ typeof(global::Gs2.Gs2Realtime.Message.PluginContainer.Types.MessageType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.ReceiveBinaryMessage), global::Gs2.Gs2Realtime.Message.ReceiveBinaryMessage.Parser, new[]{ "ConnectionId", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gs2.Gs2Realtime.Message.SendBinaryMessage), global::Gs2.Gs2Realtime.Message.SendBinaryMessage.Parser, new[]{ "Data", "TargetConnectionId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// プラグインメッセージコンテナ
  /// </summary>
  public sealed partial class PluginContainer : pb::IMessage<PluginContainer> {
    private static readonly pb::MessageParser<PluginContainer> _parser = new pb::MessageParser<PluginContainer>(() => new PluginContainer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PluginContainer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.PluginReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginContainer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginContainer(PluginContainer other) : this() {
      messageType_ = other.messageType_;
      payload_ = other.payload_ != null ? other.payload_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginContainer Clone() {
      return new PluginContainer(this);
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Gs2.Gs2Realtime.Message.PluginContainer.Types.MessageType messageType_ = 0;
    /// <summary>
    /// ペイロードの種類
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Gs2.Gs2Realtime.Message.PluginContainer.Types.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Any payload_;
    /// <summary>
    /// ペイロード
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PluginContainer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PluginContainer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (!object.Equals(Payload, other.Payload)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != 0) hash ^= MessageType.GetHashCode();
      if (payload_ != null) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MessageType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (payload_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PluginContainer other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != 0) {
        MessageType = other.MessageType;
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          Payload = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Payload.MergeFrom(other.Payload);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Gs2.Gs2Realtime.Message.PluginContainer.Types.MessageType) input.ReadEnum();
            break;
          }
          case 26: {
            if (payload_ == null) {
              Payload = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Payload);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PluginContainer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum MessageType {
        /// <summary>
        /// 受信したバイナリメッセージ
        /// </summary>
        [pbr::OriginalName("RECEIVE_BINARY_MESSAGE")] ReceiveBinaryMessage = 0,
        /// <summary>
        /// 送信するバイナリメッセージ
        /// </summary>
        [pbr::OriginalName("SEND_BINARY_MESSAGE")] SendBinaryMessage = 1,
        /// <summary>
        /// プレイヤー参加通知
        /// </summary>
        [pbr::OriginalName("JOIN_NOTIFICATION")] JoinNotification = 536870912,
        /// <summary>
        /// プレイヤー離脱通知
        /// </summary>
        [pbr::OriginalName("LEAVE_NOTIFICATION")] LeaveNotification = 536870913,
        /// <summary>
        /// プレイヤー情報更新通知
        /// </summary>
        [pbr::OriginalName("UPDATE_PROFILE_NOTIFICATION")] UpdateProfileNotification = 536870914,
        /// <summary>
        /// エラー
        /// </summary>
        [pbr::OriginalName("ERROR")] Error = 2147483647,
      }

    }
    #endregion

  }

  public sealed partial class ReceiveBinaryMessage : pb::IMessage<ReceiveBinaryMessage> {
    private static readonly pb::MessageParser<ReceiveBinaryMessage> _parser = new pb::MessageParser<ReceiveBinaryMessage>(() => new ReceiveBinaryMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReceiveBinaryMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.PluginReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReceiveBinaryMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReceiveBinaryMessage(ReceiveBinaryMessage other) : this() {
      connectionId_ = other.connectionId_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReceiveBinaryMessage Clone() {
      return new ReceiveBinaryMessage(this);
    }

    /// <summary>Field number for the "connectionId" field.</summary>
    public const int ConnectionIdFieldNumber = 2;
    private uint connectionId_;
    /// <summary>
    /// メッセージの送信元コネクションID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ConnectionId {
      get { return connectionId_; }
      set {
        connectionId_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// バイナリデータ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReceiveBinaryMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReceiveBinaryMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConnectionId != other.ConnectionId) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConnectionId != 0) hash ^= ConnectionId.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (ConnectionId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ConnectionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConnectionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConnectionId);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReceiveBinaryMessage other) {
      if (other == null) {
        return;
      }
      if (other.ConnectionId != 0) {
        ConnectionId = other.ConnectionId;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
          case 16: {
            ConnectionId = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SendBinaryMessage : pb::IMessage<SendBinaryMessage> {
    private static readonly pb::MessageParser<SendBinaryMessage> _parser = new pb::MessageParser<SendBinaryMessage>(() => new SendBinaryMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SendBinaryMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gs2.Gs2Realtime.Message.PluginReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendBinaryMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendBinaryMessage(SendBinaryMessage other) : this() {
      data_ = other.data_;
      targetConnectionId_ = other.targetConnectionId_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendBinaryMessage Clone() {
      return new SendBinaryMessage(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// バイナリデータ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "targetConnectionId" field.</summary>
    public const int TargetConnectionIdFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_targetConnectionId_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> targetConnectionId_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// 送信先コネクションID / 省略するとブロードキャスト
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> TargetConnectionId {
      get { return targetConnectionId_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SendBinaryMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SendBinaryMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      if(!targetConnectionId_.Equals(other.targetConnectionId_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      hash ^= targetConnectionId_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      targetConnectionId_.WriteTo(output, _repeated_targetConnectionId_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      size += targetConnectionId_.CalculateSize(_repeated_targetConnectionId_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SendBinaryMessage other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      targetConnectionId_.Add(other.targetConnectionId_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
          case 18:
          case 16: {
            targetConnectionId_.AddEntriesFrom(input, _repeated_targetConnectionId_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
